miniorange_saml_customer_admin_email: null
miniorange_saml_license_key: null
miniorange_saml_customer_id: ''
miniorange_saml_customer_admin_token: ''
miniorange_saml_customer_api_key: ''
miniorange_saml_force_auth: false
miniorange_saml_enable_backdoor: false
miniorange_saml_default_relaystate: ''
miniorange_saml_idp_name: Okta
miniorange_saml_idp_issuer: 'http://www.okta.com/exk1jqeqyltkRCSCo1d8'
miniorange_saml_idp_login_url: 'https://fireeye.okta.com/app/fireeye_acquiaprod_1/exk1jqeqyltkRCSCo1d8/sso/saml'
miniorange_saml_idp_logout_url: ''
miniorange_saml_idp_x509_certificate: "-----BEGIN CERTIFICATE-----\r\nMIIDnjCCAoagAwIBAgIGAV2mur8OMA0GCSqGSIb3DQEBCwUAMIGPMQswCQYDVQQG\r\nEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj\r\nbzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxEDAOBgNVBAMM\r\nB2ZpcmVleWUxHDAaBgkqhkiG9w0BCQEWDWluZm9Ab2t0YS5jb20wHhcNMTcwODAz\r\nMDYxMzAyWhcNMjcwODAzMDYxNDAxWjCBjzELMAkGA1UEBhMCVVMxEzARBgNVBAgM\r\nCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDTALBgNVBAoMBE9r\r\ndGExFDASBgNVBAsMC1NTT1Byb3ZpZGVyMRAwDgYDVQQDDAdmaXJlZXllMRwwGgYJ\r\nKoZIhvcNAQkBFg1pbmZvQG9rdGEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\r\nMIIBCgKCAQEAl1XSOCVw+a5iAlCu9tk0oLQ3WhrMKu9cTzxC2VUksuE/vQWPelVr\r\n9o6IeSwPHNILRpwuzt2jC+1D+CjXW6LRnyxGdaHxFHlL1uS4Rv5WbznBiFkBaJ7J\r\nC4qh0/emzNjzMnu0TpDd5BUkjIkdXXF+AVqmvkjglZ89yCpUwi5maDkj7iHMNINu\r\nSidxwHB+BMjGhqJIjWtHdK+lQAYgyqKyMX7kgGKufl3XRhHRjngePlX6F+yp9+Nx\r\nUjKAIoiJMSM7LS3YehvJaJdfkxNZR4o12PMwpLU/OkMnzVtcc5SwyOd99/8G/Cnh\r\nsc/bIxKHqVuevAiMq/rX11ytw+ayBOY23QIDAQABMA0GCSqGSIb3DQEBCwUAA4IB\r\nAQAc61XY4qzfjPWCR8W1kpmtdHoBZLjUNaGJvKFdC8mcHNgnFUXzuBljJ6HUGm6v\r\ndZwsgK3UNlb+WC7yRpRgDvXyy9h+CBuoaXoQ2i0/fh33uaWStDMQDYI3Z6CiJEr3\r\nXmP+OqR+zuBxJi0TuTdotwyMgQhrq8SColHfRlei4gLicwFTx+iW5UhCQVaJq6sR\r\nKsy+k5U4KnlEt56cJ6VqSDSY+9d7ZMhQNNlnIHSGSw3+PVWidHruKAAFxwJhSsM5\r\nKYG/hVr35AU4ROVcycReL6YD42CyNi/dFm7rxjciCG4W432xYWJbW/LF6X384ByN\r\nYZT8zSygFyF0h9Nti/Cg+Mop\r\n-----END CERTIFICATE-----"
miniorange_saml_response_signed: false
miniorange_saml_assertion_signed: false
miniorange_saml_enable_login: true
miniorange_saml_username_attribute: NameID
miniorange_saml_email_attribute: NameID
miniorange_saml_idp_attr1_name: ''
miniorange_saml_attr5_name: ''
miniorange_saml_idp_attr5_name: ''
miniorange_saml_attr2_name: ''
miniorange_saml_idp_attr2_name: ''
miniorange_saml_attr3_name: ''
miniorange_saml_idp_attr3_name: ''
miniorange_saml_attr4_name: ''
miniorange_saml_idp_attr4_name: ''
miniorange_saml_disable_autocreate_users: false
miniorange_saml_default_role: 'Editor user'
miniorange_saml_role1_name: ''
miniorange_saml_idp_role1_name: ''
miniorange_saml_role2_name: ''
miniorange_saml_idp_role2_name: ''
miniorange_saml_role3_name: ''
miniorange_saml_idp_role3_name: ''
miniorange_saml_role4_name: ''
miniorange_saml_idp_role4_name: ''
miniorange_saml_status: ''
miniorange_saml_customer_admin_phone: null
miniorange_saml_tx_id: null
miniorange_saml_customer_admin_password: ''
miniorange_saml_auto_redirect_to_idp: false
miniorange_saml_sp_issuer: 'https://mandiant.prod.acquia-sites.com/samlassertion'
miniorange_saml_login_by: 0
miniorange_saml_attr1_name: ''
redirect_plan_after_registration_standard: 'https://login.xecurify.com/moas/login?username=none&redirectUrl=https://login.xecurify.com/moas/initializepayment&requestOrigin=drupal8_miniorange_saml_standard_plan'
redirect_plan_after_registration_premium: 'https://login.xecurify.com/moas/login?username=none&redirectUrl=https://login.xecurify.com/moas/initializepayment&requestOrigin=drupal8_miniorange_saml_premium_plan'
redirect_plan_after_registration_enterprise: 'https://login.xecurify.com/moas/login?username=none&redirectUrl=https://login.xecurify.com/moas/initializepayment&requestOrigin=drupal8_miniorange_saml_enterprise_plan'
_core:
  default_config_hash: 7vVtKfXo09hGD7QP6jvaZjqmHoKfKKljiI74YDIwwws
miniorange_saml_nameid_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
miniorange_saml_feedback: '1'
mo_saml_tourTaken_idp_setup: true
mo_saml_tourTaken_overAllTour: true
mo_saml_tourTaken_sp_setup: true
mo_saml_tourTaken_Mapping: true
miniorange_saml_default_role_index: '2'
miniorange_saml_enable_rolemapping: true
mo_saml_tourTaken_AdvanceSettings: true
miniorange_saml_base: 'https://mandiant.prod.acquia-sites.com'
