shield_enable: false
credential_provider: shield
credentials:
  shield:
    user: ''
    pass: ''
print: 'This site is protected by a username and password.'
allow_cli: true
_core:
  default_config_hash: yHBuI_J_kdrugm0JRNsxHODZ0qQyPzejI6r1ZPacK5Q
whitelist: ''
