#!/usr/bin/env bash

#: exec_target = cli

## Resets username and password for uid=1
##
## Usage: fin build-gin

# Abort if anything fails
set -e

echo "Transpiling gin fixes styles..."
npm install -g sass
cd /var/www/docroot/modules/custom/mandiant_tweaks
sass --watch scss/gin-fixes.scss css/gin-fixes.css
