#!/usr/bin/env bash

fin config set XDEBUG_ENABLED=1 --env=local

# Copy Drupal settings
fin exec "cp \$PROJECT_ROOT/.docksal/etc/drupal/development.services.on.yml \$PROJECT_ROOT/\$DOCROOT/sites/development.services.yml"

fin up

fin drush cr
