#!/usr/bin/env bash

## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init

# Abort if anything fails
set -e
#-------------------------- Settings --------------------------------

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper Functions --------------------------------

#-------------------------- Execution --------------------------------

# Reset container services.
fin reset -f

# Initialize stack
fin project start

# Install project requirements
fin exec composer clear-cache
fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec COMPOSER_MEMORY_LIMIT=-1 composer install --no-suggest --no-interaction

# Set up blt
cd $DOCROOT_PATH
fin exec /var/www/vendor/bin/blt setup -D disable-targets.source.build.frontend=TRUE --no-interaction

# Build frontend theme for both sites.
fin exec -T /var/www/vendor/bin/blt source:build:frontend --no-interaction

cd ${PROJECT_ROOT}

# Prepare private folder (this fixes `drush cron error`).
mkdir -p files-private/default

# Clear & re-index local solr index.
echo -en "${yellow} Setting up local Solr index. ${NC}"
fin exec /var/www/vendor/bin/drush sapi-c
fin exec /var/www/vendor/bin/drush sapi-rt
fin exec /var/www/vendor/bin/drush sapi-i

# All done.
echo -en "${green_bg} DONE! ${NC}"
echo
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
