#!/usr/bin/env bash

#: exec_target = cli

## Resets username and password for uid=1
##
## Usage: fin validate

# Abort if anything fails
set -e

phpcbf \
  --standard="Drupal,DrupalPractice" -n \
  --extensions="php,module,inc,install,test,profile,theme" \
  --ignore="*.features.*,*.pages*.inc" \
  docroot/modules/custom/
